services:
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: honote
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
